use bangtandb;

CREATE TABLE User_Inf (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Balance DECIMAL(15,2) DEFAULT 0
);

CREATE TABLE Transactions_Inf (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL,
    Type VARCHAR(20) NOT NULL, -- DEPOSIT, WITHDRAW, TRANSFER
    Amount DECIMAL(15,2) NOT NULL,
    Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES User_Inf(ID)
);
